name: Check Code Review

# Trigger on pull request to the 'main' branch and on pull request reviews
on:
  pull_request:
    branches:
      - develop  # Target branch to enforce review rules
  pull_request_review:
    branches:
      - develop  # Re-run workflow on review submissions

jobs:
  check_review:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out your repository's code

      - name: Check for Code Review Approval
        id: review_check
        run: |
          REVIEWERS_TEAM="javelard"  # Replace with your actual organization/team slug
          PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
          REVIEWS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)
          REVIEW_APPROVED=$(echo $REVIEWS | jq -r '.[] | select(.state == "APPROVED") | .user.login' | grep -E "$REVIEWERS_TEAM")
          
          if [ -z "$REVIEW_APPROVED" ]; then
            echo "No approval from required reviewers."
            exit 1
          fi

      - name: Success Message
        if: success()
        run: |
          echo "Pull request is approved by the required team members."
