name: Check Code Review

# Trigger on pull request to the 'main' branch and on pull request reviews
on:
  pull_request:
    branches:
      - develop  # Target branch to enforce review rules
  pull_request_review:
    branches:
      - develop  # Re-run workflow on review submissions

jobs:
  check_review:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out your repository's code

      - name: Check for Specific User Approval
        id: review_check
        run: |
          SPECIFIED_USER="javelard"  # Replace 'username' with the GitHub username of the tester
          PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
          REVIEWS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)
          REVIEW_APPROVED=$(echo $REVIEWS | jq -r ".[] | select(.state == \"APPROVED\" and .user.login == \"$SPECIFIED_USER\")")
          
          if [ -z "$REVIEW_APPROVED" ]; then
            echo "No approval from the specified user ($SPECIFIED_USER)."
            exit 1
          fi

      - name: Success Message
        if: success()
        run: |
          echo "Pull request is approved by the specified user ($SPECIFIED_USER)."
