name: Check Code Review

on:
  pull_request:
    branches:
      - develop  # The branch you want to protect
  pull_request_review:
    branches:
      - develop  # Trigger on review submissions

jobs:
  check_review:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Code Review Approval
        id: review_check
        run: |
          REVIEWERS_TEAM="Josue9405"  # Update with your org/team
          PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
          REVIEWS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews)
          REVIEW_APPROVED=$(echo $REVIEWS | jq -r '.[] | select(.state == "APPROVED") | .user.login' | grep -E "$REVIEWERS_TEAM")
          
          if [ -z "$REVIEW_APPROVED" ]; then
            echo "No approval from required reviewers."
            exit 1
          fi

      - name: Merge Pull Request
        if: success()
        run: |
          echo "Pull request is approved by the required team members."
